// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: applications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const byJobBreakdown = `-- name: ByJobBreakdown :many
SELECT j.id AS job_id, j.title AS job_title,
       COUNT(*)::int AS total,
       COUNT(*) FILTER (WHERE a.stage = 'hired')::int AS hired,
       COUNT(*) FILTER (WHERE a.stage = 'rejected')::int AS rejected
FROM applications a
JOIN jobs j ON a.job_id = j.id
WHERE j.requisition_id = $1
GROUP BY j.id, j.title
`

type ByJobBreakdownRow struct {
	JobID    string `json:"job_id"`
	JobTitle string `json:"job_title"`
	Total    int32  `json:"total"`
	Hired    int32  `json:"hired"`
	Rejected int32  `json:"rejected"`
}

func (q *Queries) ByJobBreakdown(ctx context.Context, requisitionID pgtype.Text) ([]ByJobBreakdownRow, error) {
	rows, err := q.db.Query(ctx, byJobBreakdown, requisitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ByJobBreakdownRow{}
	for rows.Next() {
		var i ByJobBreakdownRow
		if err := rows.Scan(
			&i.JobID,
			&i.JobTitle,
			&i.Total,
			&i.Hired,
			&i.Rejected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countApplicationsByJobAndStage = `-- name: CountApplicationsByJobAndStage :many
SELECT stage, COUNT(*)::int AS count
FROM applications
WHERE job_id = $1
GROUP BY stage
`

type CountApplicationsByJobAndStageRow struct {
	Stage string `json:"stage"`
	Count int32  `json:"count"`
}

func (q *Queries) CountApplicationsByJobAndStage(ctx context.Context, jobID string) ([]CountApplicationsByJobAndStageRow, error) {
	rows, err := q.db.Query(ctx, countApplicationsByJobAndStage, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountApplicationsByJobAndStageRow{}
	for rows.Next() {
		var i CountApplicationsByJobAndStageRow
		if err := rows.Scan(&i.Stage, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (stage, candidate_id, job_id)
VALUES ('applied', $1, $2)
RETURNING id, stage, rejection_reason, rejection_notes, candidate_id, job_id, created_at, updated_at, referral_id
`

type CreateApplicationParams struct {
	CandidateID string `json:"candidate_id"`
	JobID       string `json:"job_id"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication, arg.CandidateID, arg.JobID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Stage,
		&i.RejectionReason,
		&i.RejectionNotes,
		&i.CandidateID,
		&i.JobID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReferralID,
	)
	return i, err
}

const createApplicationWithReferral = `-- name: CreateApplicationWithReferral :one
INSERT INTO applications (stage, candidate_id, job_id, referral_id)
VALUES ('applied', $1, $2, $3)
RETURNING id, stage, rejection_reason, rejection_notes, candidate_id, job_id, created_at, updated_at, referral_id
`

type CreateApplicationWithReferralParams struct {
	CandidateID string `json:"candidate_id"`
	JobID       string `json:"job_id"`
	ReferralID  string `json:"referral_id"`
}

func (q *Queries) CreateApplicationWithReferral(ctx context.Context, arg CreateApplicationWithReferralParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplicationWithReferral, arg.CandidateID, arg.JobID, arg.ReferralID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Stage,
		&i.RejectionReason,
		&i.RejectionNotes,
		&i.CandidateID,
		&i.JobID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReferralID,
	)
	return i, err
}

const setApplicationReferral = `-- name: SetApplicationReferral :exec
UPDATE applications SET referral_id = $2 WHERE id = $1
`

func (q *Queries) SetApplicationReferral(ctx context.Context, id string, referralID string) error {
	_, err := q.db.Exec(ctx, setApplicationReferral, id, referralID)
	return err
}

const funnelByRequisition = `-- name: FunnelByRequisition :many
SELECT a.stage, COUNT(*)::int AS count
FROM applications a
JOIN jobs j ON a.job_id = j.id
WHERE j.requisition_id = $1
GROUP BY a.stage
`

type FunnelByRequisitionRow struct {
	Stage string `json:"stage"`
	Count int32  `json:"count"`
}

func (q *Queries) FunnelByRequisition(ctx context.Context, requisitionID pgtype.Text) ([]FunnelByRequisitionRow, error) {
	rows, err := q.db.Query(ctx, funnelByRequisition, requisitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FunnelByRequisitionRow{}
	for rows.Next() {
		var i FunnelByRequisitionRow
		if err := rows.Scan(&i.Stage, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT id, stage, rejection_reason, rejection_notes, candidate_id, job_id, created_at, updated_at, referral_id FROM applications WHERE id = $1
`

func (q *Queries) GetApplicationByID(ctx context.Context, id string) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByID, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Stage,
		&i.RejectionReason,
		&i.RejectionNotes,
		&i.CandidateID,
		&i.JobID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReferralID,
	)
	return i, err
}

const getApplicationWithDetails = `-- name: GetApplicationWithDetails :one
SELECT a.id, a.stage, a.rejection_reason, a.rejection_notes, a.candidate_id, a.job_id, a.created_at, a.updated_at,
       a.referral_id,
       c.name AS candidate_name, c.email AS candidate_email, c.phone AS candidate_phone,
       c.resume_url AS candidate_resume_url, c.company AS candidate_company, c.linkedin_url AS candidate_linkedin_url,
       j.title AS job_title, j.location AS job_location, j.department AS job_department,
       o.name AS org_name,
       ru.name AS referred_by_name
FROM applications a
JOIN candidates c ON a.candidate_id = c.id
JOIN jobs j ON a.job_id = j.id
JOIN organizations o ON j.organization_id = o.id
LEFT JOIN referrals ref ON a.referral_id = ref.id
LEFT JOIN users ru ON ref.referrer_id = ru.id
WHERE a.id = $1
`

type GetApplicationWithDetailsRow struct {
	ID                    string             `json:"id"`
	Stage                 string             `json:"stage"`
	RejectionReason       pgtype.Text        `json:"rejection_reason"`
	RejectionNotes        pgtype.Text        `json:"rejection_notes"`
	CandidateID           string             `json:"candidate_id"`
	JobID                 string             `json:"job_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	ReferralID            pgtype.Text        `json:"referral_id"`
	CandidateName         string             `json:"candidate_name"`
	CandidateEmail        string             `json:"candidate_email"`
	CandidatePhone        pgtype.Text        `json:"candidate_phone"`
	CandidateResumeUrl    pgtype.Text        `json:"candidate_resume_url"`
	CandidateCompany      pgtype.Text        `json:"candidate_company"`
	CandidateLinkedinUrl  pgtype.Text        `json:"candidate_linkedin_url"`
	JobTitle              string             `json:"job_title"`
	JobLocation           pgtype.Text        `json:"job_location"`
	JobDepartment         pgtype.Text        `json:"job_department"`
	OrgName               string             `json:"org_name"`
	ReferredByName        pgtype.Text        `json:"referred_by_name"`
}

func (q *Queries) GetApplicationWithDetails(ctx context.Context, id string) (GetApplicationWithDetailsRow, error) {
	row := q.db.QueryRow(ctx, getApplicationWithDetails, id)
	var i GetApplicationWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Stage,
		&i.RejectionReason,
		&i.RejectionNotes,
		&i.CandidateID,
		&i.JobID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReferralID,
		&i.CandidateName,
		&i.CandidateEmail,
		&i.CandidatePhone,
		&i.CandidateResumeUrl,
		&i.CandidateCompany,
		&i.CandidateLinkedinUrl,
		&i.JobTitle,
		&i.JobLocation,
		&i.JobDepartment,
		&i.OrgName,
		&i.ReferredByName,
	)
	return i, err
}

const listApplicationsByCandidate = `-- name: ListApplicationsByCandidate :many
SELECT a.id, a.stage, a.rejection_reason, a.rejection_notes, a.candidate_id, a.job_id, a.created_at, a.updated_at, j.title AS job_title, j.status AS job_status
FROM applications a
JOIN jobs j ON a.job_id = j.id
WHERE a.candidate_id = $1
ORDER BY a.created_at DESC
`

type ListApplicationsByCandidateRow struct {
	ID              string             `json:"id"`
	Stage           string             `json:"stage"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	RejectionNotes  pgtype.Text        `json:"rejection_notes"`
	CandidateID     string             `json:"candidate_id"`
	JobID           string             `json:"job_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	JobTitle        string             `json:"job_title"`
	JobStatus       string             `json:"job_status"`
}

func (q *Queries) ListApplicationsByCandidate(ctx context.Context, candidateID string) ([]ListApplicationsByCandidateRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsByCandidate, candidateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationsByCandidateRow{}
	for rows.Next() {
		var i ListApplicationsByCandidateRow
		if err := rows.Scan(
			&i.ID,
			&i.Stage,
			&i.RejectionReason,
			&i.RejectionNotes,
			&i.CandidateID,
			&i.JobID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JobTitle,
			&i.JobStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByJob = `-- name: ListApplicationsByJob :many
SELECT a.id, a.stage, a.rejection_reason, a.rejection_notes, a.candidate_id, a.job_id, a.created_at, a.updated_at,
       c.name AS candidate_name, c.email AS candidate_email,
       c.resume_url AS candidate_resume_url, c.company AS candidate_company
FROM applications a
JOIN candidates c ON a.candidate_id = c.id
WHERE a.job_id = $1
ORDER BY a.created_at DESC
`

type ListApplicationsByJobRow struct {
	ID                 string             `json:"id"`
	Stage              string             `json:"stage"`
	RejectionReason    pgtype.Text        `json:"rejection_reason"`
	RejectionNotes     pgtype.Text        `json:"rejection_notes"`
	CandidateID        string             `json:"candidate_id"`
	JobID              string             `json:"job_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CandidateName      string             `json:"candidate_name"`
	CandidateEmail     string             `json:"candidate_email"`
	CandidateResumeUrl pgtype.Text        `json:"candidate_resume_url"`
	CandidateCompany   pgtype.Text        `json:"candidate_company"`
}

func (q *Queries) ListApplicationsByJob(ctx context.Context, jobID string) ([]ListApplicationsByJobRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationsByJobRow{}
	for rows.Next() {
		var i ListApplicationsByJobRow
		if err := rows.Scan(
			&i.ID,
			&i.Stage,
			&i.RejectionReason,
			&i.RejectionNotes,
			&i.CandidateID,
			&i.JobID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CandidateName,
			&i.CandidateEmail,
			&i.CandidateResumeUrl,
			&i.CandidateCompany,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByJobForInterviewer = `-- name: ListApplicationsByJobForInterviewer :many
SELECT a.id, a.stage, a.rejection_reason, a.rejection_notes, a.candidate_id, a.job_id, a.created_at, a.updated_at,
       c.name AS candidate_name, c.email AS candidate_email,
       c.resume_url AS candidate_resume_url, c.company AS candidate_company
FROM applications a
JOIN candidates c ON a.candidate_id = c.id
JOIN interview_assignments ia ON ia.application_id = a.id
WHERE a.job_id = $1 AND ia.interviewer_id = $2
ORDER BY a.created_at DESC
`

type ListApplicationsByJobForInterviewerParams struct {
	JobID         string `json:"job_id"`
	InterviewerID string `json:"interviewer_id"`
}

type ListApplicationsByJobForInterviewerRow struct {
	ID                 string             `json:"id"`
	Stage              string             `json:"stage"`
	RejectionReason    pgtype.Text        `json:"rejection_reason"`
	RejectionNotes     pgtype.Text        `json:"rejection_notes"`
	CandidateID        string             `json:"candidate_id"`
	JobID              string             `json:"job_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CandidateName      string             `json:"candidate_name"`
	CandidateEmail     string             `json:"candidate_email"`
	CandidateResumeUrl pgtype.Text        `json:"candidate_resume_url"`
	CandidateCompany   pgtype.Text        `json:"candidate_company"`
}

func (q *Queries) ListApplicationsByJobForInterviewer(ctx context.Context, arg ListApplicationsByJobForInterviewerParams) ([]ListApplicationsByJobForInterviewerRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsByJobForInterviewer, arg.JobID, arg.InterviewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationsByJobForInterviewerRow{}
	for rows.Next() {
		var i ListApplicationsByJobForInterviewerRow
		if err := rows.Scan(
			&i.ID,
			&i.Stage,
			&i.RejectionReason,
			&i.RejectionNotes,
			&i.CandidateID,
			&i.JobID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CandidateName,
			&i.CandidateEmail,
			&i.CandidateResumeUrl,
			&i.CandidateCompany,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectionsByRequisition = `-- name: RejectionsByRequisition :many
SELECT a.rejection_reason, COUNT(*)::int AS count
FROM applications a
JOIN jobs j ON a.job_id = j.id
WHERE j.requisition_id = $1 AND a.stage = 'rejected' AND a.rejection_reason IS NOT NULL
GROUP BY a.rejection_reason
`

type RejectionsByRequisitionRow struct {
	RejectionReason pgtype.Text `json:"rejection_reason"`
	Count           int32       `json:"count"`
}

func (q *Queries) RejectionsByRequisition(ctx context.Context, requisitionID pgtype.Text) ([]RejectionsByRequisitionRow, error) {
	rows, err := q.db.Query(ctx, rejectionsByRequisition, requisitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RejectionsByRequisitionRow{}
	for rows.Next() {
		var i RejectionsByRequisitionRow
		if err := rows.Scan(&i.RejectionReason, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplicationStage = `-- name: UpdateApplicationStage :one
UPDATE applications
SET stage = $2, rejection_reason = $3, rejection_notes = $4, updated_at = now()
WHERE id = $1
RETURNING id, stage, rejection_reason, rejection_notes, candidate_id, job_id, created_at, updated_at, referral_id
`

type UpdateApplicationStageParams struct {
	ID              string      `json:"id"`
	Stage           string      `json:"stage"`
	RejectionReason pgtype.Text `json:"rejection_reason"`
	RejectionNotes  pgtype.Text `json:"rejection_notes"`
}

func (q *Queries) UpdateApplicationStage(ctx context.Context, arg UpdateApplicationStageParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplicationStage,
		arg.ID,
		arg.Stage,
		arg.RejectionReason,
		arg.RejectionNotes,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Stage,
		&i.RejectionReason,
		&i.RejectionNotes,
		&i.CandidateID,
		&i.JobID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReferralID,
	)
	return i, err
}
