// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: candidate_contacts.sql

package db

import (
	"context"
)

const listContactsByCandidate = `-- name: ListContactsByCandidate :many
SELECT id, candidate_id, category, label, value, created_at FROM candidate_contacts WHERE candidate_id = $1 ORDER BY category, label
`

func (q *Queries) ListContactsByCandidate(ctx context.Context, candidateID string) ([]CandidateContact, error) {
	rows, err := q.db.Query(ctx, listContactsByCandidate, candidateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CandidateContact{}
	for rows.Next() {
		var i CandidateContact
		if err := rows.Scan(
			&i.ID,
			&i.CandidateID,
			&i.Category,
			&i.Label,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCandidateContact = `-- name: CreateCandidateContact :one
INSERT INTO candidate_contacts (candidate_id, category, label, value)
VALUES ($1, $2, $3, $4) RETURNING id, candidate_id, category, label, value, created_at
`

type CreateCandidateContactParams struct {
	CandidateID string `json:"candidate_id"`
	Category    string `json:"category"`
	Label       string `json:"label"`
	Value       string `json:"value"`
}

func (q *Queries) CreateCandidateContact(ctx context.Context, arg CreateCandidateContactParams) (CandidateContact, error) {
	row := q.db.QueryRow(ctx, createCandidateContact,
		arg.CandidateID,
		arg.Category,
		arg.Label,
		arg.Value,
	)
	var i CandidateContact
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.Category,
		&i.Label,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCandidateContact = `-- name: DeleteCandidateContact :exec
DELETE FROM candidate_contacts WHERE id = $1 AND candidate_id = $2
`

type DeleteCandidateContactParams struct {
	ID          string `json:"id"`
	CandidateID string `json:"candidate_id"`
}

func (q *Queries) DeleteCandidateContact(ctx context.Context, arg DeleteCandidateContactParams) error {
	_, err := q.db.Exec(ctx, deleteCandidateContact, arg.ID, arg.CandidateID)
	return err
}
