// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: candidates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCandidateByID = `-- name: GetCandidateByID :one
SELECT id, name, email, phone, resume_url, resume_filename, organization_id, created_at, updated_at FROM candidates WHERE id = $1 AND organization_id = $2
`

type GetCandidateByIDParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) GetCandidateByID(ctx context.Context, arg GetCandidateByIDParams) (Candidate, error) {
	row := q.db.QueryRow(ctx, getCandidateByID, arg.ID, arg.OrganizationID)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.ResumeUrl,
		&i.ResumeFilename,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCandidatesByOrg = `-- name: ListCandidatesByOrg :many
SELECT id, name, email, phone, resume_url, resume_filename, organization_id, created_at, updated_at FROM candidates WHERE organization_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListCandidatesByOrg(ctx context.Context, organizationID string) ([]Candidate, error) {
	rows, err := q.db.Query(ctx, listCandidatesByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Candidate{}
	for rows.Next() {
		var i Candidate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.ResumeUrl,
			&i.ResumeFilename,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCandidates = `-- name: SearchCandidates :many
SELECT id, name, email, phone, resume_url, resume_filename, organization_id, created_at, updated_at FROM candidates
WHERE organization_id = $1
  AND (name ILIKE '%' || $2 || '%' OR email ILIKE '%' || $2 || '%')
ORDER BY created_at DESC
`

type SearchCandidatesParams struct {
	OrganizationID string      `json:"organization_id"`
	Column2        pgtype.Text `json:"column_2"`
}

func (q *Queries) SearchCandidates(ctx context.Context, arg SearchCandidatesParams) ([]Candidate, error) {
	rows, err := q.db.Query(ctx, searchCandidates, arg.OrganizationID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Candidate{}
	for rows.Next() {
		var i Candidate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.ResumeUrl,
			&i.ResumeFilename,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCandidate = `-- name: UpsertCandidate :one
INSERT INTO candidates (name, email, phone, resume_url, resume_filename, organization_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (email, organization_id) DO UPDATE
SET name = EXCLUDED.name, phone = EXCLUDED.phone,
    resume_url = COALESCE(EXCLUDED.resume_url, candidates.resume_url),
    resume_filename = COALESCE(EXCLUDED.resume_filename, candidates.resume_filename),
    updated_at = now()
RETURNING id, name, email, phone, resume_url, resume_filename, organization_id, created_at, updated_at
`

type UpsertCandidateParams struct {
	Name           string      `json:"name"`
	Email          string      `json:"email"`
	Phone          pgtype.Text `json:"phone"`
	ResumeUrl      pgtype.Text `json:"resume_url"`
	ResumeFilename pgtype.Text `json:"resume_filename"`
	OrganizationID string      `json:"organization_id"`
}

func (q *Queries) UpsertCandidate(ctx context.Context, arg UpsertCandidateParams) (Candidate, error) {
	row := q.db.QueryRow(ctx, upsertCandidate,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.ResumeUrl,
		arg.ResumeFilename,
		arg.OrganizationID,
	)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.ResumeUrl,
		&i.ResumeFilename,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
