// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interview_schedules.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertCalendarConnection = `-- name: UpsertCalendarConnection :one
INSERT INTO user_calendar_connections (user_id, provider, access_token, refresh_token, token_expiry, calendar_email)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, provider) DO UPDATE
SET access_token = EXCLUDED.access_token, refresh_token = EXCLUDED.refresh_token,
    token_expiry = EXCLUDED.token_expiry, calendar_email = EXCLUDED.calendar_email, updated_at = now()
RETURNING id, user_id, provider, access_token, refresh_token, token_expiry, calendar_email, created_at, updated_at
`

type UpsertCalendarConnectionParams struct {
	UserID        string             `json:"user_id"`
	Provider      string             `json:"provider"`
	AccessToken   string             `json:"access_token"`
	RefreshToken  string             `json:"refresh_token"`
	TokenExpiry   pgtype.Timestamptz `json:"token_expiry"`
	CalendarEmail string             `json:"calendar_email"`
}

func (q *Queries) UpsertCalendarConnection(ctx context.Context, arg UpsertCalendarConnectionParams) (UserCalendarConnection, error) {
	row := q.db.QueryRow(ctx, upsertCalendarConnection,
		arg.UserID, arg.Provider, arg.AccessToken, arg.RefreshToken, arg.TokenExpiry, arg.CalendarEmail,
	)
	var i UserCalendarConnection
	err := row.Scan(&i.ID, &i.UserID, &i.Provider, &i.AccessToken, &i.RefreshToken, &i.TokenExpiry, &i.CalendarEmail, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getCalendarConnection = `-- name: GetCalendarConnection :one
SELECT id, user_id, provider, access_token, refresh_token, token_expiry, calendar_email, created_at, updated_at FROM user_calendar_connections WHERE user_id = $1 AND provider = $2
`

type GetCalendarConnectionParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) GetCalendarConnection(ctx context.Context, arg GetCalendarConnectionParams) (UserCalendarConnection, error) {
	row := q.db.QueryRow(ctx, getCalendarConnection, arg.UserID, arg.Provider)
	var i UserCalendarConnection
	err := row.Scan(&i.ID, &i.UserID, &i.Provider, &i.AccessToken, &i.RefreshToken, &i.TokenExpiry, &i.CalendarEmail, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getCalendarConnectionByUser = `-- name: GetCalendarConnectionByUser :one
SELECT id, user_id, provider, access_token, refresh_token, token_expiry, calendar_email, created_at, updated_at FROM user_calendar_connections WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetCalendarConnectionByUser(ctx context.Context, userID string) (UserCalendarConnection, error) {
	row := q.db.QueryRow(ctx, getCalendarConnectionByUser, userID)
	var i UserCalendarConnection
	err := row.Scan(&i.ID, &i.UserID, &i.Provider, &i.AccessToken, &i.RefreshToken, &i.TokenExpiry, &i.CalendarEmail, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteCalendarConnection = `-- name: DeleteCalendarConnection :exec
DELETE FROM user_calendar_connections WHERE user_id = $1
`

func (q *Queries) DeleteCalendarConnection(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteCalendarConnection, userID)
	return err
}

const createInterviewSchedule = `-- name: CreateInterviewSchedule :one
INSERT INTO interview_schedules (application_id, token, duration_minutes, location, meeting_url, notes, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, application_id, token, status, duration_minutes, location, meeting_url, notes, created_by, confirmed_at, created_at
`

type CreateInterviewScheduleParams struct {
	ApplicationID   string      `json:"application_id"`
	Token           string      `json:"token"`
	DurationMinutes int32       `json:"duration_minutes"`
	Location        pgtype.Text `json:"location"`
	MeetingUrl      pgtype.Text `json:"meeting_url"`
	Notes           pgtype.Text `json:"notes"`
	CreatedBy       string      `json:"created_by"`
}

func (q *Queries) CreateInterviewSchedule(ctx context.Context, arg CreateInterviewScheduleParams) (InterviewSchedule, error) {
	row := q.db.QueryRow(ctx, createInterviewSchedule,
		arg.ApplicationID, arg.Token, arg.DurationMinutes, arg.Location, arg.MeetingUrl, arg.Notes, arg.CreatedBy,
	)
	var i InterviewSchedule
	err := row.Scan(&i.ID, &i.ApplicationID, &i.Token, &i.Status, &i.DurationMinutes, &i.Location, &i.MeetingUrl, &i.Notes, &i.CreatedBy, &i.ConfirmedAt, &i.CreatedAt)
	return i, err
}

const getScheduleByToken = `-- name: GetScheduleByToken :one
SELECT s.id, s.application_id, s.token, s.status, s.duration_minutes, s.location, s.meeting_url, s.notes, s.created_by, s.confirmed_at, s.created_at,
       j.title AS job_title, c.name AS candidate_name, c.email AS candidate_email, o.name AS org_name
FROM interview_schedules s
JOIN applications a ON s.application_id = a.id
JOIN jobs j ON a.job_id = j.id
JOIN candidates c ON a.candidate_id = c.id
JOIN organizations o ON j.organization_id = o.id
WHERE s.token = $1
`

type GetScheduleByTokenRow struct {
	ID              string             `json:"id"`
	ApplicationID   string             `json:"application_id"`
	Token           string             `json:"token"`
	Status          string             `json:"status"`
	DurationMinutes int32              `json:"duration_minutes"`
	Location        pgtype.Text        `json:"location"`
	MeetingUrl      pgtype.Text        `json:"meeting_url"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedBy       string             `json:"created_by"`
	ConfirmedAt     pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	JobTitle        string             `json:"job_title"`
	CandidateName   string             `json:"candidate_name"`
	CandidateEmail  string             `json:"candidate_email"`
	OrgName         string             `json:"org_name"`
}

func (q *Queries) GetScheduleByToken(ctx context.Context, token string) (GetScheduleByTokenRow, error) {
	row := q.db.QueryRow(ctx, getScheduleByToken, token)
	var i GetScheduleByTokenRow
	err := row.Scan(&i.ID, &i.ApplicationID, &i.Token, &i.Status, &i.DurationMinutes, &i.Location, &i.MeetingUrl, &i.Notes, &i.CreatedBy, &i.ConfirmedAt, &i.CreatedAt,
		&i.JobTitle, &i.CandidateName, &i.CandidateEmail, &i.OrgName)
	return i, err
}

const listSchedulesByApplication = `-- name: ListSchedulesByApplication :many
SELECT s.id, s.application_id, s.token, s.status, s.duration_minutes, s.location, s.meeting_url, s.notes, s.created_by, s.confirmed_at, s.created_at, u.name AS created_by_name
FROM interview_schedules s
JOIN users u ON s.created_by = u.id
WHERE s.application_id = $1
ORDER BY s.created_at DESC
`

type ListSchedulesByApplicationRow struct {
	ID              string             `json:"id"`
	ApplicationID   string             `json:"application_id"`
	Token           string             `json:"token"`
	Status          string             `json:"status"`
	DurationMinutes int32              `json:"duration_minutes"`
	Location        pgtype.Text        `json:"location"`
	MeetingUrl      pgtype.Text        `json:"meeting_url"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedBy       string             `json:"created_by"`
	ConfirmedAt     pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CreatedByName   string             `json:"created_by_name"`
}

func (q *Queries) ListSchedulesByApplication(ctx context.Context, applicationID string) ([]ListSchedulesByApplicationRow, error) {
	rows, err := q.db.Query(ctx, listSchedulesByApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchedulesByApplicationRow{}
	for rows.Next() {
		var i ListSchedulesByApplicationRow
		if err := rows.Scan(&i.ID, &i.ApplicationID, &i.Token, &i.Status, &i.DurationMinutes, &i.Location, &i.MeetingUrl, &i.Notes, &i.CreatedBy, &i.ConfirmedAt, &i.CreatedAt, &i.CreatedByName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const updateScheduleStatus = `-- name: UpdateScheduleStatus :exec
UPDATE interview_schedules SET status = $2, confirmed_at = CASE WHEN $2 = 'confirmed' THEN now() ELSE confirmed_at END WHERE id = $1
`

func (q *Queries) UpdateScheduleStatus(ctx context.Context, id string, status string) error {
	_, err := q.db.Exec(ctx, updateScheduleStatus, id, status)
	return err
}

const createInterviewSlot = `-- name: CreateInterviewSlot :one
INSERT INTO interview_slots (schedule_id, start_time, end_time) VALUES ($1, $2, $3)
RETURNING id, schedule_id, start_time, end_time, selected
`

type CreateInterviewSlotParams struct {
	ScheduleID string             `json:"schedule_id"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) CreateInterviewSlot(ctx context.Context, arg CreateInterviewSlotParams) (InterviewSlot, error) {
	row := q.db.QueryRow(ctx, createInterviewSlot, arg.ScheduleID, arg.StartTime, arg.EndTime)
	var i InterviewSlot
	err := row.Scan(&i.ID, &i.ScheduleID, &i.StartTime, &i.EndTime, &i.Selected)
	return i, err
}

const listSlotsBySchedule = `-- name: ListSlotsBySchedule :many
SELECT id, schedule_id, start_time, end_time, selected FROM interview_slots WHERE schedule_id = $1 ORDER BY start_time
`

func (q *Queries) ListSlotsBySchedule(ctx context.Context, scheduleID string) ([]InterviewSlot, error) {
	rows, err := q.db.Query(ctx, listSlotsBySchedule, scheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InterviewSlot{}
	for rows.Next() {
		var i InterviewSlot
		if err := rows.Scan(&i.ID, &i.ScheduleID, &i.StartTime, &i.EndTime, &i.Selected); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const selectSlot = `-- name: SelectSlot :exec
UPDATE interview_slots SET selected = (id = $2) WHERE schedule_id = $1
`

func (q *Queries) SelectSlot(ctx context.Context, scheduleID string, slotID string) error {
	_, err := q.db.Exec(ctx, selectSlot, scheduleID, slotID)
	return err
}

const addScheduleInterviewer = `-- name: AddScheduleInterviewer :exec
INSERT INTO interview_schedule_interviewers (schedule_id, user_id) VALUES ($1, $2)
`

func (q *Queries) AddScheduleInterviewer(ctx context.Context, scheduleID string, userID string) error {
	_, err := q.db.Exec(ctx, addScheduleInterviewer, scheduleID, userID)
	return err
}

const listScheduleInterviewers = `-- name: ListScheduleInterviewers :many
SELECT si.schedule_id, si.user_id, si.calendar_event_id, u.name, u.email
FROM interview_schedule_interviewers si
JOIN users u ON si.user_id = u.id
WHERE si.schedule_id = $1
`

type ListScheduleInterviewersRow struct {
	ScheduleID      string      `json:"schedule_id"`
	UserID          string      `json:"user_id"`
	CalendarEventID pgtype.Text `json:"calendar_event_id"`
	Name            string      `json:"name"`
	Email           string      `json:"email"`
}

func (q *Queries) ListScheduleInterviewers(ctx context.Context, scheduleID string) ([]ListScheduleInterviewersRow, error) {
	rows, err := q.db.Query(ctx, listScheduleInterviewers, scheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduleInterviewersRow{}
	for rows.Next() {
		var i ListScheduleInterviewersRow
		if err := rows.Scan(&i.ScheduleID, &i.UserID, &i.CalendarEventID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const setCalendarEventID = `-- name: SetCalendarEventID :exec
UPDATE interview_schedule_interviewers SET calendar_event_id = $3 WHERE schedule_id = $1 AND user_id = $2
`

func (q *Queries) SetCalendarEventID(ctx context.Context, scheduleID string, userID string, eventID pgtype.Text) error {
	_, err := q.db.Exec(ctx, setCalendarEventID, scheduleID, userID, eventID)
	return err
}
