// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interview_assignments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInterviewAssignment = `-- name: CreateInterviewAssignment :one
INSERT INTO interview_assignments (application_id, interviewer_id)
VALUES ($1, $2)
RETURNING id, application_id, interviewer_id, created_at
`

type CreateInterviewAssignmentParams struct {
	ApplicationID string `json:"application_id"`
	InterviewerID string `json:"interviewer_id"`
}

func (q *Queries) CreateInterviewAssignment(ctx context.Context, arg CreateInterviewAssignmentParams) (InterviewAssignment, error) {
	row := q.db.QueryRow(ctx, createInterviewAssignment, arg.ApplicationID, arg.InterviewerID)
	var i InterviewAssignment
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.InterviewerID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInterviewAssignment = `-- name: DeleteInterviewAssignment :exec
DELETE FROM interview_assignments
WHERE application_id = $1 AND interviewer_id = $2
`

type DeleteInterviewAssignmentParams struct {
	ApplicationID string `json:"application_id"`
	InterviewerID string `json:"interviewer_id"`
}

func (q *Queries) DeleteInterviewAssignment(ctx context.Context, arg DeleteInterviewAssignmentParams) error {
	_, err := q.db.Exec(ctx, deleteInterviewAssignment, arg.ApplicationID, arg.InterviewerID)
	return err
}

const listApplicationsByInterviewer = `-- name: ListApplicationsByInterviewer :many
SELECT a.id, a.stage, a.rejection_reason, a.rejection_notes, a.candidate_id, a.job_id, a.created_at, a.updated_at, c.name AS candidate_name, c.email AS candidate_email,
       c.resume_url AS candidate_resume_url,
       j.title AS job_title, j.id AS job_id
FROM interview_assignments ia
JOIN applications a ON ia.application_id = a.id
JOIN candidates c ON a.candidate_id = c.id
JOIN jobs j ON a.job_id = j.id
WHERE ia.interviewer_id = $1 AND j.organization_id = $2
ORDER BY a.created_at DESC
`

type ListApplicationsByInterviewerParams struct {
	InterviewerID  string `json:"interviewer_id"`
	OrganizationID string `json:"organization_id"`
}

type ListApplicationsByInterviewerRow struct {
	ID                 string             `json:"id"`
	Stage              string             `json:"stage"`
	RejectionReason    pgtype.Text        `json:"rejection_reason"`
	RejectionNotes     pgtype.Text        `json:"rejection_notes"`
	CandidateID        string             `json:"candidate_id"`
	JobID              string             `json:"job_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CandidateName      string             `json:"candidate_name"`
	CandidateEmail     string             `json:"candidate_email"`
	CandidateResumeUrl pgtype.Text        `json:"candidate_resume_url"`
	JobTitle           string             `json:"job_title"`
	JobID_2            string             `json:"job_id_2"`
}

func (q *Queries) ListApplicationsByInterviewer(ctx context.Context, arg ListApplicationsByInterviewerParams) ([]ListApplicationsByInterviewerRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsByInterviewer, arg.InterviewerID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationsByInterviewerRow{}
	for rows.Next() {
		var i ListApplicationsByInterviewerRow
		if err := rows.Scan(
			&i.ID,
			&i.Stage,
			&i.RejectionReason,
			&i.RejectionNotes,
			&i.CandidateID,
			&i.JobID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CandidateName,
			&i.CandidateEmail,
			&i.CandidateResumeUrl,
			&i.JobTitle,
			&i.JobID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInterviewersByApplication = `-- name: ListInterviewersByApplication :many
SELECT ia.id, ia.application_id, ia.interviewer_id, ia.created_at, u.name AS interviewer_name, u.email AS interviewer_email
FROM interview_assignments ia
JOIN users u ON ia.interviewer_id = u.id
WHERE ia.application_id = $1
ORDER BY ia.created_at
`

type ListInterviewersByApplicationRow struct {
	ID               string             `json:"id"`
	ApplicationID    string             `json:"application_id"`
	InterviewerID    string             `json:"interviewer_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	InterviewerName  string             `json:"interviewer_name"`
	InterviewerEmail string             `json:"interviewer_email"`
}

func (q *Queries) ListInterviewersByApplication(ctx context.Context, applicationID string) ([]ListInterviewersByApplicationRow, error) {
	rows, err := q.db.Query(ctx, listInterviewersByApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInterviewersByApplicationRow{}
	for rows.Next() {
		var i ListInterviewersByApplicationRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.InterviewerID,
			&i.CreatedAt,
			&i.InterviewerName,
			&i.InterviewerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
