// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interview_feedback.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInterviewFeedback = `-- name: CreateInterviewFeedback :one
INSERT INTO interview_feedback (application_id, stage, interview_type, recommendation, content, author_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, application_id, stage, interview_type, recommendation, content, author_id, created_at, updated_at
`

type CreateInterviewFeedbackParams struct {
	ApplicationID  string      `json:"application_id"`
	Stage          string      `json:"stage"`
	InterviewType  pgtype.Text `json:"interview_type"`
	Recommendation string      `json:"recommendation"`
	Content        string      `json:"content"`
	AuthorID       string      `json:"author_id"`
}

func (q *Queries) CreateInterviewFeedback(ctx context.Context, arg CreateInterviewFeedbackParams) (InterviewFeedback, error) {
	row := q.db.QueryRow(ctx, createInterviewFeedback, arg.ApplicationID, arg.Stage, arg.InterviewType, arg.Recommendation, arg.Content, arg.AuthorID)
	var i InterviewFeedback
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Stage,
		&i.InterviewType,
		&i.Recommendation,
		&i.Content,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFeedbackByApplication = `-- name: ListFeedbackByApplication :many
SELECT f.id, f.application_id, f.stage, f.interview_type, f.recommendation, f.content, f.author_id, f.created_at, f.updated_at, u.name AS author_name
FROM interview_feedback f
JOIN users u ON f.author_id = u.id
WHERE f.application_id = $1
ORDER BY f.stage, f.created_at
`

type ListFeedbackByApplicationRow struct {
	ID             string             `json:"id"`
	ApplicationID  string             `json:"application_id"`
	Stage          string             `json:"stage"`
	InterviewType  pgtype.Text        `json:"interview_type"`
	Recommendation string             `json:"recommendation"`
	Content        string             `json:"content"`
	AuthorID       string             `json:"author_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AuthorName     string             `json:"author_name"`
}

func (q *Queries) ListFeedbackByApplication(ctx context.Context, applicationID string) ([]ListFeedbackByApplicationRow, error) {
	rows, err := q.db.Query(ctx, listFeedbackByApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedbackByApplicationRow{}
	for rows.Next() {
		var i ListFeedbackByApplicationRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Stage,
			&i.InterviewType,
			&i.Recommendation,
			&i.Content,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInterviewFeedback = `-- name: UpdateInterviewFeedback :one
UPDATE interview_feedback
SET recommendation = $2, content = $3, interview_type = $4, updated_at = now()
WHERE id = $1
RETURNING id, application_id, stage, interview_type, recommendation, content, author_id, created_at, updated_at
`

type UpdateInterviewFeedbackParams struct {
	ID             string      `json:"id"`
	Recommendation string      `json:"recommendation"`
	Content        string      `json:"content"`
	InterviewType  pgtype.Text `json:"interview_type"`
}

func (q *Queries) UpdateInterviewFeedback(ctx context.Context, arg UpdateInterviewFeedbackParams) (InterviewFeedback, error) {
	row := q.db.QueryRow(ctx, updateInterviewFeedback, arg.ID, arg.Recommendation, arg.Content, arg.InterviewType)
	var i InterviewFeedback
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Stage,
		&i.InterviewType,
		&i.Recommendation,
		&i.Content,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInterviewFeedback = `-- name: DeleteInterviewFeedback :exec
DELETE FROM interview_feedback WHERE id = $1
`

func (q *Queries) DeleteInterviewFeedback(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteInterviewFeedback, id)
	return err
}

const getInterviewFeedbackByID = `-- name: GetInterviewFeedbackByID :one
SELECT id, application_id, stage, interview_type, recommendation, content, author_id, created_at, updated_at
FROM interview_feedback WHERE id = $1
`

func (q *Queries) GetInterviewFeedbackByID(ctx context.Context, id string) (InterviewFeedback, error) {
	row := q.db.QueryRow(ctx, getInterviewFeedbackByID, id)
	var i InterviewFeedback
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Stage,
		&i.InterviewType,
		&i.Recommendation,
		&i.Content,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
