// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :one
UPDATE invitations SET accepted_at = now() WHERE id = $1 RETURNING id, email, role, token, organization_id, expires_at, accepted_at, created_at
`

func (q *Queries) AcceptInvitation(ctx context.Context, id string) (Invitation, error) {
	row := q.db.QueryRow(ctx, acceptInvitation, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.OrganizationID,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (email, role, organization_id, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, email, role, token, organization_id, expires_at, accepted_at, created_at
`

type CreateInvitationParams struct {
	Email          string             `json:"email"`
	Role           string             `json:"role"`
	OrganizationID string             `json:"organization_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.Email,
		arg.Role,
		arg.OrganizationID,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.OrganizationID,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT id, email, role, token, organization_id, expires_at, accepted_at, created_at FROM invitations WHERE token = $1 AND accepted_at IS NULL AND expires_at > now()
`

func (q *Queries) GetInvitationByToken(ctx context.Context, token string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByToken, token)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.OrganizationID,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvitationsByOrg = `-- name: ListInvitationsByOrg :many
SELECT id, email, role, token, organization_id, expires_at, accepted_at, created_at FROM invitations WHERE organization_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListInvitationsByOrg(ctx context.Context, organizationID string) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitationsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.Token,
			&i.OrganizationID,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
