// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (title, company_blurb, team_details, responsibilities, qualifications, closing_statement, location, department, salary, status, requisition_id, organization_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, title, company_blurb, team_details, responsibilities, qualifications, closing_statement, location, department, salary, status, requisition_id, organization_id, created_at, updated_at
`

type CreateJobParams struct {
	Title            string      `json:"title"`
	CompanyBlurb     string      `json:"company_blurb"`
	TeamDetails      string      `json:"team_details"`
	Responsibilities string      `json:"responsibilities"`
	Qualifications   string      `json:"qualifications"`
	ClosingStatement string      `json:"closing_statement"`
	Location         pgtype.Text `json:"location"`
	Department       pgtype.Text `json:"department"`
	Salary           pgtype.Text `json:"salary"`
	Status           string      `json:"status"`
	RequisitionID    pgtype.Text `json:"requisition_id"`
	OrganizationID   string      `json:"organization_id"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Title,
		arg.CompanyBlurb,
		arg.TeamDetails,
		arg.Responsibilities,
		arg.Qualifications,
		arg.ClosingStatement,
		arg.Location,
		arg.Department,
		arg.Salary,
		arg.Status,
		arg.RequisitionID,
		arg.OrganizationID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CompanyBlurb,
		&i.TeamDetails,
		&i.Responsibilities,
		&i.Qualifications,
		&i.ClosingStatement,
		&i.Location,
		&i.Department,
		&i.Salary,
		&i.Status,
		&i.RequisitionID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, title, company_blurb, team_details, responsibilities, qualifications, closing_statement, location, department, salary, status, requisition_id, organization_id, created_at, updated_at FROM jobs WHERE id = $1 AND organization_id = $2
`

type GetJobByIDParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) GetJobByID(ctx context.Context, arg GetJobByIDParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, arg.ID, arg.OrganizationID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CompanyBlurb,
		&i.TeamDetails,
		&i.Responsibilities,
		&i.Qualifications,
		&i.ClosingStatement,
		&i.Location,
		&i.Department,
		&i.Salary,
		&i.Status,
		&i.RequisitionID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobPublic = `-- name: GetJobPublic :one
SELECT id, title, company_blurb, team_details, responsibilities, qualifications, closing_statement, location, department, salary, status, requisition_id, organization_id, created_at, updated_at FROM jobs WHERE id = $1 AND status = 'open'
`

func (q *Queries) GetJobPublic(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRow(ctx, getJobPublic, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CompanyBlurb,
		&i.TeamDetails,
		&i.Responsibilities,
		&i.Qualifications,
		&i.ClosingStatement,
		&i.Location,
		&i.Department,
		&i.Salary,
		&i.Status,
		&i.RequisitionID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobsByHiringManager = `-- name: ListJobsByHiringManager :many
SELECT j.id, j.title, j.company_blurb, j.team_details, j.responsibilities, j.qualifications, j.closing_statement, j.location, j.department, j.salary, j.status, j.requisition_id, j.organization_id, j.created_at, j.updated_at FROM jobs j
JOIN requisitions r ON j.requisition_id = r.id
WHERE j.organization_id = $1 AND r.hiring_manager_id = $2
ORDER BY j.created_at DESC
`

type ListJobsByHiringManagerParams struct {
	OrganizationID  string      `json:"organization_id"`
	HiringManagerID pgtype.Text `json:"hiring_manager_id"`
}

func (q *Queries) ListJobsByHiringManager(ctx context.Context, arg ListJobsByHiringManagerParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByHiringManager, arg.OrganizationID, arg.HiringManagerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CompanyBlurb,
			&i.TeamDetails,
			&i.Responsibilities,
			&i.Qualifications,
			&i.ClosingStatement,
			&i.Location,
			&i.Department,
			&i.Salary,
			&i.Status,
			&i.RequisitionID,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByInterviewer = `-- name: ListJobsByInterviewer :many
SELECT DISTINCT j.id, j.title, j.company_blurb, j.team_details, j.responsibilities, j.qualifications, j.closing_statement, j.location, j.department, j.salary, j.status, j.requisition_id, j.organization_id, j.created_at, j.updated_at FROM jobs j
JOIN applications a ON a.job_id = j.id
JOIN interview_assignments ia ON ia.application_id = a.id
WHERE j.organization_id = $1 AND ia.interviewer_id = $2
ORDER BY j.created_at DESC
`

type ListJobsByInterviewerParams struct {
	OrganizationID string `json:"organization_id"`
	InterviewerID  string `json:"interviewer_id"`
}

func (q *Queries) ListJobsByInterviewer(ctx context.Context, arg ListJobsByInterviewerParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByInterviewer, arg.OrganizationID, arg.InterviewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CompanyBlurb,
			&i.TeamDetails,
			&i.Responsibilities,
			&i.Qualifications,
			&i.ClosingStatement,
			&i.Location,
			&i.Department,
			&i.Salary,
			&i.Status,
			&i.RequisitionID,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByOrg = `-- name: ListJobsByOrg :many
SELECT id, title, company_blurb, team_details, responsibilities, qualifications, closing_statement, location, department, salary, status, requisition_id, organization_id, created_at, updated_at FROM jobs WHERE organization_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListJobsByOrg(ctx context.Context, organizationID string) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CompanyBlurb,
			&i.TeamDetails,
			&i.Responsibilities,
			&i.Qualifications,
			&i.ClosingStatement,
			&i.Location,
			&i.Department,
			&i.Salary,
			&i.Status,
			&i.RequisitionID,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByRequisition = `-- name: ListJobsByRequisition :many
SELECT id, title, company_blurb, team_details, responsibilities, qualifications, closing_statement, location, department, salary, status, requisition_id, organization_id, created_at, updated_at FROM jobs WHERE requisition_id = $1 AND organization_id = $2 ORDER BY created_at DESC
`

type ListJobsByRequisitionParams struct {
	RequisitionID  pgtype.Text `json:"requisition_id"`
	OrganizationID string      `json:"organization_id"`
}

func (q *Queries) ListJobsByRequisition(ctx context.Context, arg ListJobsByRequisitionParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByRequisition, arg.RequisitionID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CompanyBlurb,
			&i.TeamDetails,
			&i.Responsibilities,
			&i.Qualifications,
			&i.ClosingStatement,
			&i.Location,
			&i.Department,
			&i.Salary,
			&i.Status,
			&i.RequisitionID,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenJobsByOrgSlug = `-- name: ListOpenJobsByOrgSlug :many
SELECT j.id, j.title, j.company_blurb, j.team_details, j.responsibilities, j.qualifications, j.closing_statement, j.location, j.department, j.salary, j.status, j.requisition_id, j.organization_id, j.created_at, j.updated_at FROM jobs j
JOIN organizations o ON j.organization_id = o.id
WHERE o.slug = $1 AND j.status = 'open'
ORDER BY j.created_at DESC
`

func (q *Queries) ListOpenJobsByOrgSlug(ctx context.Context, slug string) ([]Job, error) {
	rows, err := q.db.Query(ctx, listOpenJobsByOrgSlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CompanyBlurb,
			&i.TeamDetails,
			&i.Responsibilities,
			&i.Qualifications,
			&i.ClosingStatement,
			&i.Location,
			&i.Department,
			&i.Salary,
			&i.Status,
			&i.RequisitionID,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET title = $2, company_blurb = $3, team_details = $4, responsibilities = $5, qualifications = $6,
    closing_statement = $7, location = $8, department = $9, salary = $10, status = $11,
    requisition_id = $12, updated_at = now()
WHERE id = $1 AND organization_id = $13
RETURNING id, title, company_blurb, team_details, responsibilities, qualifications, closing_statement, location, department, salary, status, requisition_id, organization_id, created_at, updated_at
`

type UpdateJobParams struct {
	ID               string      `json:"id"`
	Title            string      `json:"title"`
	CompanyBlurb     string      `json:"company_blurb"`
	TeamDetails      string      `json:"team_details"`
	Responsibilities string      `json:"responsibilities"`
	Qualifications   string      `json:"qualifications"`
	ClosingStatement string      `json:"closing_statement"`
	Location         pgtype.Text `json:"location"`
	Department       pgtype.Text `json:"department"`
	Salary           pgtype.Text `json:"salary"`
	Status           string      `json:"status"`
	RequisitionID    pgtype.Text `json:"requisition_id"`
	OrganizationID   string      `json:"organization_id"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.ID,
		arg.Title,
		arg.CompanyBlurb,
		arg.TeamDetails,
		arg.Responsibilities,
		arg.Qualifications,
		arg.ClosingStatement,
		arg.Location,
		arg.Department,
		arg.Salary,
		arg.Status,
		arg.RequisitionID,
		arg.OrganizationID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CompanyBlurb,
		&i.TeamDetails,
		&i.Responsibilities,
		&i.Qualifications,
		&i.ClosingStatement,
		&i.Location,
		&i.Department,
		&i.Salary,
		&i.Status,
		&i.RequisitionID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
