// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID              string             `json:"id"`
	Stage           string             `json:"stage"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	RejectionNotes  pgtype.Text        `json:"rejection_notes"`
	CandidateID     string             `json:"candidate_id"`
	JobID           string             `json:"job_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Candidate struct {
	ID             string             `json:"id"`
	Name           string             `json:"name"`
	Email          string             `json:"email"`
	Phone          pgtype.Text        `json:"phone"`
	ResumeUrl      pgtype.Text        `json:"resume_url"`
	ResumeFilename pgtype.Text        `json:"resume_filename"`
	OrganizationID string             `json:"organization_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Invitation struct {
	ID             string             `json:"id"`
	Email          string             `json:"email"`
	Role           string             `json:"role"`
	Token          string             `json:"token"`
	OrganizationID string             `json:"organization_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt     pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Job struct {
	ID             string             `json:"id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	Location       pgtype.Text        `json:"location"`
	Department     pgtype.Text        `json:"department"`
	Salary         pgtype.Text        `json:"salary"`
	Status         string             `json:"status"`
	RequisitionID  pgtype.Text        `json:"requisition_id"`
	OrganizationID string             `json:"organization_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Note struct {
	ID            string             `json:"id"`
	Content       string             `json:"content"`
	ApplicationID string             `json:"application_id"`
	AuthorID      string             `json:"author_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Organization struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	LogoUrl   pgtype.Text        `json:"logo_url"`
	Website   pgtype.Text        `json:"website"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Requisition struct {
	ID              string             `json:"id"`
	Title           string             `json:"title"`
	Level           pgtype.Text        `json:"level"`
	Department      pgtype.Text        `json:"department"`
	TargetHires     int32              `json:"target_hires"`
	Status          string             `json:"status"`
	HiringManagerID pgtype.Text        `json:"hiring_manager_id"`
	OrganizationID  string             `json:"organization_id"`
	OpenedAt        pgtype.Timestamptz `json:"opened_at"`
	ClosedAt        pgtype.Timestamptz `json:"closed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type StageTransition struct {
	ID            string             `json:"id"`
	ApplicationID string             `json:"application_id"`
	FromStage     pgtype.Text        `json:"from_stage"`
	ToStage       string             `json:"to_stage"`
	MovedByID     pgtype.Text        `json:"moved_by_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             string             `json:"id"`
	Email          string             `json:"email"`
	Name           string             `json:"name"`
	PasswordHash   string             `json:"password_hash"`
	Role           string             `json:"role"`
	OrganizationID string             `json:"organization_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
