// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (content, application_id, author_id)
VALUES ($1, $2, $3)
RETURNING id, content, application_id, author_id, created_at
`

type CreateNoteParams struct {
	Content       string `json:"content"`
	ApplicationID string `json:"application_id"`
	AuthorID      string `json:"author_id"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote, arg.Content, arg.ApplicationID, arg.AuthorID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.ApplicationID,
		&i.AuthorID,
		&i.CreatedAt,
	)
	return i, err
}

const listNotesByApplication = `-- name: ListNotesByApplication :many
SELECT n.id, n.content, n.application_id, n.author_id, n.created_at, u.name AS author_name
FROM notes n
JOIN users u ON n.author_id = u.id
WHERE n.application_id = $1
ORDER BY n.created_at
`

type ListNotesByApplicationRow struct {
	ID            string             `json:"id"`
	Content       string             `json:"content"`
	ApplicationID string             `json:"application_id"`
	AuthorID      string             `json:"author_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	AuthorName    string             `json:"author_name"`
}

func (q *Queries) ListNotesByApplication(ctx context.Context, applicationID string) ([]ListNotesByApplicationRow, error) {
	rows, err := q.db.Query(ctx, listNotesByApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotesByApplicationRow{}
	for rows.Next() {
		var i ListNotesByApplicationRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.ApplicationID,
			&i.AuthorID,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
