// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, logo_url, website, default_company_blurb, default_closing_statement, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.Website,
		&i.DefaultCompanyBlurb,
		&i.DefaultClosingStatement,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgDefaults = `-- name: GetOrgDefaults :one
SELECT default_company_blurb, default_closing_statement FROM organizations WHERE id = $1
`

type GetOrgDefaultsRow struct {
	DefaultCompanyBlurb     string `json:"default_company_blurb"`
	DefaultClosingStatement string `json:"default_closing_statement"`
}

func (q *Queries) GetOrgDefaults(ctx context.Context, id string) (GetOrgDefaultsRow, error) {
	row := q.db.QueryRow(ctx, getOrgDefaults, id)
	var i GetOrgDefaultsRow
	err := row.Scan(&i.DefaultCompanyBlurb, &i.DefaultClosingStatement)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, logo_url, website, default_company_blurb, default_closing_statement, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.Website,
		&i.DefaultCompanyBlurb,
		&i.DefaultClosingStatement,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, logo_url, website, default_company_blurb, default_closing_statement, created_at, updated_at FROM organizations WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.Website,
		&i.DefaultCompanyBlurb,
		&i.DefaultClosingStatement,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrgDefaults = `-- name: UpdateOrgDefaults :one
UPDATE organizations
SET default_company_blurb = $2, default_closing_statement = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, slug, logo_url, website, default_company_blurb, default_closing_statement, created_at, updated_at
`

type UpdateOrgDefaultsParams struct {
	ID                      string `json:"id"`
	DefaultCompanyBlurb     string `json:"default_company_blurb"`
	DefaultClosingStatement string `json:"default_closing_statement"`
}

func (q *Queries) UpdateOrgDefaults(ctx context.Context, arg UpdateOrgDefaultsParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrgDefaults, arg.ID, arg.DefaultCompanyBlurb, arg.DefaultClosingStatement)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.Website,
		&i.DefaultCompanyBlurb,
		&i.DefaultClosingStatement,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET name = $2, slug = $3, logo_url = $4, website = $5, updated_at = now()
WHERE id = $1
RETURNING id, name, slug, logo_url, website, default_company_blurb, default_closing_statement, created_at, updated_at
`

type UpdateOrganizationParams struct {
	ID      string      `json:"id"`
	Name    string      `json:"name"`
	Slug    string      `json:"slug"`
	LogoUrl pgtype.Text `json:"logo_url"`
	Website pgtype.Text `json:"website"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.LogoUrl,
		arg.Website,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.Website,
		&i.DefaultCompanyBlurb,
		&i.DefaultClosingStatement,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
