// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requisitions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countHiredByRequisition = `-- name: CountHiredByRequisition :one
SELECT COUNT(*) FROM applications a
JOIN jobs j ON a.job_id = j.id
WHERE j.requisition_id = $1 AND a.stage = 'hired'
`

func (q *Queries) CountHiredByRequisition(ctx context.Context, requisitionID pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countHiredByRequisition, requisitionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRequisition = `-- name: CreateRequisition :one
INSERT INTO requisitions (title, level, department, target_hires, hiring_manager_id, organization_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, level, department, target_hires, status, hiring_manager_id, organization_id, opened_at, closed_at, created_at, updated_at
`

type CreateRequisitionParams struct {
	Title           string      `json:"title"`
	Level           pgtype.Text `json:"level"`
	Department      pgtype.Text `json:"department"`
	TargetHires     int32       `json:"target_hires"`
	HiringManagerID pgtype.Text `json:"hiring_manager_id"`
	OrganizationID  string      `json:"organization_id"`
}

func (q *Queries) CreateRequisition(ctx context.Context, arg CreateRequisitionParams) (Requisition, error) {
	row := q.db.QueryRow(ctx, createRequisition,
		arg.Title,
		arg.Level,
		arg.Department,
		arg.TargetHires,
		arg.HiringManagerID,
		arg.OrganizationID,
	)
	var i Requisition
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Level,
		&i.Department,
		&i.TargetHires,
		&i.Status,
		&i.HiringManagerID,
		&i.OrganizationID,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRequisitionByID = `-- name: GetRequisitionByID :one
SELECT id, title, level, department, target_hires, status, hiring_manager_id, organization_id, opened_at, closed_at, created_at, updated_at FROM requisitions WHERE id = $1 AND organization_id = $2
`

type GetRequisitionByIDParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) GetRequisitionByID(ctx context.Context, arg GetRequisitionByIDParams) (Requisition, error) {
	row := q.db.QueryRow(ctx, getRequisitionByID, arg.ID, arg.OrganizationID)
	var i Requisition
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Level,
		&i.Department,
		&i.TargetHires,
		&i.Status,
		&i.HiringManagerID,
		&i.OrganizationID,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRequisitionsByOrg = `-- name: ListRequisitionsByOrg :many
SELECT id, title, level, department, target_hires, status, hiring_manager_id, organization_id, opened_at, closed_at, created_at, updated_at FROM requisitions WHERE organization_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListRequisitionsByOrg(ctx context.Context, organizationID string) ([]Requisition, error) {
	rows, err := q.db.Query(ctx, listRequisitionsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Requisition{}
	for rows.Next() {
		var i Requisition
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Level,
			&i.Department,
			&i.TargetHires,
			&i.Status,
			&i.HiringManagerID,
			&i.OrganizationID,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequisition = `-- name: UpdateRequisition :one
UPDATE requisitions
SET title = $2, level = $3, department = $4, target_hires = $5,
    status = $6, hiring_manager_id = $7, closed_at = $8, updated_at = now()
WHERE id = $1 AND organization_id = $9
RETURNING id, title, level, department, target_hires, status, hiring_manager_id, organization_id, opened_at, closed_at, created_at, updated_at
`

type UpdateRequisitionParams struct {
	ID              string             `json:"id"`
	Title           string             `json:"title"`
	Level           pgtype.Text        `json:"level"`
	Department      pgtype.Text        `json:"department"`
	TargetHires     int32              `json:"target_hires"`
	Status          string             `json:"status"`
	HiringManagerID pgtype.Text        `json:"hiring_manager_id"`
	ClosedAt        pgtype.Timestamptz `json:"closed_at"`
	OrganizationID  string             `json:"organization_id"`
}

func (q *Queries) UpdateRequisition(ctx context.Context, arg UpdateRequisitionParams) (Requisition, error) {
	row := q.db.QueryRow(ctx, updateRequisition,
		arg.ID,
		arg.Title,
		arg.Level,
		arg.Department,
		arg.TargetHires,
		arg.Status,
		arg.HiringManagerID,
		arg.ClosedAt,
		arg.OrganizationID,
	)
	var i Requisition
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Level,
		&i.Department,
		&i.TargetHires,
		&i.Status,
		&i.HiringManagerID,
		&i.OrganizationID,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
