// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stage_transitions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStageTransition = `-- name: CreateStageTransition :one
INSERT INTO stage_transitions (application_id, from_stage, to_stage, moved_by_id)
VALUES ($1, $2, $3, $4)
RETURNING id, application_id, from_stage, to_stage, moved_by_id, created_at
`

type CreateStageTransitionParams struct {
	ApplicationID string      `json:"application_id"`
	FromStage     pgtype.Text `json:"from_stage"`
	ToStage       string      `json:"to_stage"`
	MovedByID     pgtype.Text `json:"moved_by_id"`
}

func (q *Queries) CreateStageTransition(ctx context.Context, arg CreateStageTransitionParams) (StageTransition, error) {
	row := q.db.QueryRow(ctx, createStageTransition,
		arg.ApplicationID,
		arg.FromStage,
		arg.ToStage,
		arg.MovedByID,
	)
	var i StageTransition
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.FromStage,
		&i.ToStage,
		&i.MovedByID,
		&i.CreatedAt,
	)
	return i, err
}

const listTransitionsByApplication = `-- name: ListTransitionsByApplication :many
SELECT st.id, st.application_id, st.from_stage, st.to_stage, st.moved_by_id, st.created_at, u.name AS moved_by_name
FROM stage_transitions st
LEFT JOIN users u ON st.moved_by_id = u.id
WHERE st.application_id = $1
ORDER BY st.created_at
`

type ListTransitionsByApplicationRow struct {
	ID            string             `json:"id"`
	ApplicationID string             `json:"application_id"`
	FromStage     pgtype.Text        `json:"from_stage"`
	ToStage       string             `json:"to_stage"`
	MovedByID     pgtype.Text        `json:"moved_by_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	MovedByName   pgtype.Text        `json:"moved_by_name"`
}

func (q *Queries) ListTransitionsByApplication(ctx context.Context, applicationID string) ([]ListTransitionsByApplicationRow, error) {
	rows, err := q.db.Query(ctx, listTransitionsByApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransitionsByApplicationRow{}
	for rows.Next() {
		var i ListTransitionsByApplicationRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.FromStage,
			&i.ToStage,
			&i.MovedByID,
			&i.CreatedAt,
			&i.MovedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
