// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team.sql

package db

import (
	"context"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1 AND organization_id = $2
`

type DeleteUserParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) error {
	_, err := q.db.Exec(ctx, deleteUser, arg.ID, arg.OrganizationID)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users SET role = $2, updated_at = now()
WHERE id = $1 AND organization_id = $3
RETURNING id, email, name, password_hash, role, organization_id, created_at, updated_at
`

type UpdateUserRoleParams struct {
	ID             string `json:"id"`
	Role           string `json:"role"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role, arg.OrganizationID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
